### ISSUE TITLE
why new RegCM versions remove the RF interface of the CMIP5 dataset 

### ISSUE THREAD

**Issue by ARS-niango** [ICTP/RegCM#13]
HelIo,
I have just installed RegCM4.7.1, but when i try to use CMIP5 RF data, i found it is not supported, which in the icbc code:
    if ( dattyp(4:5) == 'RF' ) then
      write(stderr,*) 'THIS CODE IS NOT SUPPORTED.'
      write(stderr,*) 'CHOSE ONE SCENARIO CODE ',dattyp(1:3),'(26-45-60-85).'
      call die('icbc','Unknown dattyp',1)
i found in the early RegCM version like RegCM4.0 it support it.  I just wonder why RF interface of the CMIP5 dataset is removed? 
Thank you.

**Comment by graziano-giuliani** [comment]
Just use the scenario code. The historical data are selected if the date is < 2005-12-01. This allows for non interrupted  ICBC creation. The same historical data are selected whatever the future scenario, and a specific code was considered redundant.
