### ISSUE TITLE
Compilation without CLM45 

### ISSUE THREAD

**Issue by DesmetQuentin** [ICTP/RegCM#17]
Hi!

Just to notify you there is an inconsistency between _mpplib/mod_regcm_types.F90_ (lines 466 to 472) and _mod_atm_stub.F90_ (lines 493 to 498) for the definition and memory allocation of some parameters of _lms_. The quoted lines in _mod_atm_stub.F90_ should be inside a _#ifdef CLM45_ (or reversely in _mod_regcm_types.F90_).
Maybe I am missing something though...

Cheers,
Quentin

**Comment by graziano-giuliani** [comment]
The compilation of the mod_atm_stub.F90 is conditional to the CLM45 enabled compilation. The clmsa (Community Land Model Stand Alone) program is compiled only if the CLM4.5 library is compiled. If we do not compile the CLM45, no clmsa program, no nedd to compile the mod_atm_stub object.  This is in the Makefile.am in Main (line ~106)

if DO_COMPILE_LIBCLM45
bin_PROGRAMS = regcm clmsa
else
bin_PROGRAMS = regcm
endif

**Comment by DesmetQuentin** [comment]
Oh thank you very much !
Then I must have messed up the Makefile.am somewhere cause the compilation failed at these lines.
It's all my bad.
