### ISSUE TITLE
floating divide by zero error

### ISSUE THREAD

**Issue by DesmetQuentin** [ICTP/RegCM#18]
Hello,

I'm the only one in my team to have this problem, so I guess I did something wrong...
I get a _floating divide by zero_ error at line 848 of _mod_tendendy.F90_ for a **restart run** with **_idynamic = 2_**. I have checked the array by printing them in debug files, and the zeros appear on external points.
The error disappears when I move the _exchange_ call of _sfs%psdota_ at line 800 in _mod_init.F90_ to between line 805 and 806.
Is there some parameterization I missed, which would prevent doing this?

Cheers,
Quentin

**Comment by graziano-giuliani** [comment]
Thanks Quentin, You are correct.

**Comment by DesmetQuentin** [comment]
I'm glad to help !
