### ISSUE TITLE
chemsimtype errors

### ISSUE THREAD

**Issue by praveenvatsh** [ICTP/RegCM#23]
**I got errors while using chemsimtype = 'AERO' below,**

Forcing scenario from dattyp to RCP8.5
 -------------- FATAL CALLED ---------------
  Fatal in file: mod_che_ncio.F90 at line:      516
 NO CODED FREQUENCY IN CHEMISS FILE
 -------------------------------------------
 mod_che_ncio.F90 :      516:            1
 Abort called by computing node            0 at 2022-06-30 09:10:47.402 +0530
 Execution terminated because of runtime error
Abort(1) on node 0 (rank 0 in comm 496): application called MPI_Abort(comm=0x84000002, 1) - process 0
srun: error: cn007: tasks 288-299: Exited with exit code 1
srun: error: cn002: tasks 48-95: Exited with exit code 1
srun: error: cn005: tasks 192-239: Exited with exit code 1
srun: error: cn004: tasks 144-191: Exited with exit code 1
srun: error: cn003: tasks 96-143: Exited with exit code 1
srun: error: cn006: tasks 240-287: Exited with exit code 1
srun: error: cn001: tasks 0-47: Exited with exit code 1

**Similarly, I got errors while using chemsimtype = 'DCCB' below,**

Forcing scenario from dattyp to RCP8.5
 Cannot open required file TUVGRID2.
 -------------- FATAL CALLED ---------------
  Fatal in file: mod_che_start.F90 at line:      460
 TUVGRID2 NOT FOUND
 -------------------------------------------
 Abort called by computing node          299 at 2022-06-30 09:11:56.273 +0530
 Execution terminated because of runtime error
Abort(1) on node 299 (rank 299 in comm 496): application called MPI_Abort(comm=0x84000001, 1) - process 299
 Cannot open required file TUVGRID2.
 -------------- FATAL CALLED ---------------
  Fatal in file: mod_che_start.F90 at line:      460
 TUVGRID2 NOT FOUND
 -------------------------------------------
 Abort called by computing node           14 at 2022-06-30 09:11:56.279 +0530
 Execution terminated because of runtime error
Abort(1) on node 14 (rank 14 in comm 496): application called MPI_Abort(comm=0x84000001, 1) - process 14

The test simulation of five days is completed successfully with chemsimtype = 'DUST.'
Please, someone, help me to solve the above problems.

**Comment by graziano-giuliani** [comment]
Assuming you have prepared the CHEMISS file using the cdo script "interp_emissions" from the model, can you please post here the ourput from:
ncdump -h input/DOMNAME_CHEMISS.nc
where DOMNAME is the namelist user choice for domname in terrainparam?

**Comment by praveenvatsh** [comment]
netcdf SouthAsia_SDDRE_CHEMISS {
dimensions:
        time = UNLIMITED ; // (1 currently)
        x = 200 ;
        y = 160 ;
        nv4 = 4 ;
        lev = 1 ;
variables:
        float time(time) ;
                time:standard_name = "time" ;
                time:long_name = "time" ;
                time:units = "month since 1940-01-15 00:00:00" ;
                time:calendar = "standard" ;
                time:axis = "T" ;
        float lon(y, x) ;
                lon:standard_name = "longitude" ;
                lon:long_name = "longitude" ;
                lon:units = "degrees_east" ;
                lon:_CoordinateAxisType = "Lon" ;
                lon:bounds = "lon_bnds" ;
        float lon_bnds(y, x, nv4) ;
        float lat(y, x) ;
                lat:standard_name = "latitude" ;
                lat:long_name = "latitude" ;
                lat:units = "degrees_north" ;
                lat:_CoordinateAxisType = "Lat" ;
                lat:bounds = "lat_bnds" ;
        float lat_bnds(y, x, nv4) ;
        float lev(lev) ;
                lev:long_name = "level index" ;
                lev:units = "level" ;
                lev:axis = "Z" ;
        float ALD2_flux(time, lev, y, x) ;
                ALD2_flux:long_name = "flux of ALD2" ;
                ALD2_flux:units = "Kg m-2 s-1" ;
                ALD2_flux:coordinates = "lat lon" ;
                ALD2_flux:molar_mass = 1. ;
        float height(lev) ;
                height:long_name = "emission height" ;
                height:units = "m" ;
        float AONE_flux(time, lev, y, x) ;
                AONE_flux:long_name = "flux of AONE" ;
                AONE_flux:units = "Kg m-2 s-1" ;
                AONE_flux:coordinates = "lat lon" ;
                AONE_flux:molar_mass = 1. ;
        float height_2(lev) ;
                height_2:long_name = "emission height" ;
                height_2:units = "m" ;
        float BC_flux(time, lev, y, x) ;
                BC_flux:long_name = "flux of BC" ;
                BC_flux:units = "Kg m-2 s-1" ;
                BC_flux:coordinates = "lat lon" ;
                BC_flux:molar_mass = 1. ;
        float height_3(lev) ;
                height_3:long_name = "emission height" ;
                height_3:units = "m" ;
        float C2H6_flux(time, lev, y, x) ;
                C2H6_flux:long_name = "flux of C2H6" ;
                C2H6_flux:units = "Kg m-2 s-1" ;
                C2H6_flux:coordinates = "lat lon" ;
                C2H6_flux:molar_mass = 1. ;
        float height_4(lev) ;
                height_4:long_name = "emission height" ;
                height_4:units = "m" ;
        float CH3OH_flux(time, lev, y, x) ;
                CH3OH_flux:long_name = "flux of CH3OH" ;
                CH3OH_flux:units = "Kg m-2 s-1" ;
                CH3OH_flux:coordinates = "lat lon" ;
                CH3OH_flux:molar_mass = 1. ;
        float height_5(lev) ;
                height_5:long_name = "emission height" ;
                height_5:units = "m" ;
        float CH4_flux(time, lev, y, x) ;
                CH4_flux:long_name = "flux of CH4" ;
                CH4_flux:units = "Kg m-2 s-1" ;
                CH4_flux:coordinates = "lat lon" ;
                CH4_flux:molar_mass = 1. ;
        float height_6(lev) ;
                height_6:long_name = "emission height" ;
                height_6:units = "m" ;
        float CO_flux(time, lev, y, x) ;
                CO_flux:long_name = "flux of CO" ;
                CO_flux:units = "Kg m-2 s-1" ;
                CO_flux:coordinates = "lat lon" ;
                CO_flux:molar_mass = 1. ;
        float height_7(lev) ;
                height_7:long_name = "emission height" ;
                height_7:units = "m" ;
        float ETH_flux(time, lev, y, x) ;
                ETH_flux:long_name = "flux of ETH" ;
                ETH_flux:units = "Kg m-2 s-1" ;
                ETH_flux:coordinates = "lat lon" ;
                ETH_flux:molar_mass = 1. ;
        float height_8(lev) ;
                height_8:long_name = "emission height" ;
                height_8:units = "m" ;
        float HCHO_flux(time, lev, y, x) ;
                HCHO_flux:long_name = "flux of HCHO" ;
                HCHO_flux:units = "Kg m-2 s-1" ;
                HCHO_flux:coordinates = "lat lon" ;
                HCHO_flux:molar_mass = 1. ;
        float height_9(lev) ;
                height_9:long_name = "emission height" ;
                height_9:units = "m" ;
        float NH3_flux(time, lev, y, x) ;
                NH3_flux:long_name = "flux of NH3" ;
                NH3_flux:units = "Kg m-2 s-1" ;
                NH3_flux:coordinates = "lat lon" ;
                NH3_flux:molar_mass = 1. ;
        float height_10(lev) ;
                height_10:long_name = "emission height" ;
                height_10:units = "m" ;
        float NOx_flux(time, lev, y, x) ;
                NOx_flux:long_name = "flux of NOx" ;
                NOx_flux:units = "Kg m-2 s-1" ;
                NOx_flux:coordinates = "lat lon" ;
                NOx_flux:molar_mass = 1. ;
        float height_11(lev) ;
                height_11:long_name = "emission height" ;
                height_11:units = "m" ;
        float OC_flux(time, lev, y, x) ;
                OC_flux:long_name = "flux of OC" ;
                OC_flux:units = "Kg m-2 s-1" ;
                OC_flux:coordinates = "lat lon" ;
                OC_flux:molar_mass = 1. ;
        float height_12(lev) ;
                height_12:long_name = "emission height" ;
                height_12:units = "m" ;
        float OLEI_flux(time, lev, y, x) ;
                OLEI_flux:long_name = "flux of OLEI" ;
                OLEI_flux:units = "Kg m-2 s-1" ;
                OLEI_flux:coordinates = "lat lon" ;
                OLEI_flux:molar_mass = 1. ;
        float height_13(lev) ;
                height_13:long_name = "emission height" ;
                height_13:units = "m" ;
        float OLET_flux(time, lev, y, x) ;
                OLET_flux:long_name = "flux of OLET" ;
                OLET_flux:units = "Kg m-2 s-1" ;
                OLET_flux:coordinates = "lat lon" ;
                OLET_flux:molar_mass = 1. ;
        float height_14(lev) ;
                height_14:long_name = "emission height" ;
                height_14:units = "m" ;
        float PAR_flux(time, lev, y, x) ;
                PAR_flux:long_name = "flux of PAR" ;
                PAR_flux:units = "Kg m-2 s-1" ;
                PAR_flux:coordinates = "lat lon" ;
                PAR_flux:molar_mass = 1. ;
        float height_15(lev) ;
                height_15:long_name = "emission height" ;
                height_15:units = "m" ;
        float RCOOH_flux(time, lev, y, x) ;
                RCOOH_flux:long_name = "flux of RCOOH" ;
                RCOOH_flux:units = "Kg m-2 s-1" ;
                RCOOH_flux:coordinates = "lat lon" ;
                RCOOH_flux:molar_mass = 1. ;
        float height_16(lev) ;
                height_16:long_name = "emission height" ;
                height_16:units = "m" ;
        float SO2_flux(time, lev, y, x) ;
                SO2_flux:long_name = "flux of SO2" ;
                SO2_flux:units = "Kg m-2 s-1" ;
                SO2_flux:coordinates = "lat lon" ;
                SO2_flux:molar_mass = 1. ;
        float height_17(lev) ;
                height_17:long_name = "emission height" ;
                height_17:units = "m" ;
        float TOL_flux(time, lev, y, x) ;
                TOL_flux:long_name = "flux of TOL" ;
                TOL_flux:units = "Kg m-2 s-1" ;
                TOL_flux:coordinates = "lat lon" ;
                TOL_flux:molar_mass = 1. ;
        float height_18(lev) ;
                height_18:long_name = "emission height" ;
                height_18:units = "m" ;
        float XYL_flux(time, lev, y, x) ;
                XYL_flux:long_name = "flux of XYL" ;
                XYL_flux:units = "Kg m-2 s-1" ;
                XYL_flux:coordinates = "lat lon" ;
                XYL_flux:molar_mass = 1. ;
        float height_19(lev) ;
                height_19:long_name = "emission height" ;
                height_19:units = "m" ;
        float ISOP_BIO_flux(time, lev, y, x) ;
                ISOP_BIO_flux:long_name = "flux of ISOP_BIO" ;
                ISOP_BIO_flux:units = "Kg m-2 s-1" ;
                ISOP_BIO_flux:coordinates = "lat lon" ;
                ISOP_BIO_flux:molar_mass = 1. ;
        float height_20(lev) ;
                height_20:long_name = "emission height" ;
                height_20:units = "m" ;

// global attributes:
                :CDI = "Climate Data Interface version 2.0.3 (https://mpimet.mpg.de/cdi)" ;
                :Conventions = "CF-1.6" ;
                :created_with = "emcre Version 0.4" ;
                :date = "20220628" ;
                :time = "031524.595+0530" ;
                :namelist = "\n",
                        "OUTPUT= \'./output/RCP85_ALD2_bb.nc\', \n",
                        "SPECIES= \'ALD2\', \n",
                        "TIME FREQUENCY= \'monthly\', \n",
                        "OUT UNIT= \'Kg m-2 s-1                                                                                                                                                                                              \', \n",
                        "GLOBAL_SCALE= \'   1.0000000000000000\', \n",
                        "INTERPOLATION= \'linear\', \n",
                        "MOLARMASS= \'   1.0000000000000000\', \n",
                        "YEAR_START= 1940, \n",
                        "YEAR_END= 2100, \n",
                        "HEIGHT=    0.0000000000000000, \n",
                        "INPUTPATH= \'/home/praveen/RegCM_Data/emissions/RCP_Emissions\', \n",
                        "SOURCE(   1) : \', \n",
                        "FRAC(   1)=\' 1.000\', \n",
                        "1940\',IPCC_GriddedBiomassBurningEmissions_other_alkanals_decadalmonthlymean1940_v1.nc, \n",
                        "1950\',IPCC_GriddedBiomassBurningEmissions_other_alkanals_decadalmonthlymean1950_v1.nc, \n",
                        "1960\',IPCC_GriddedBiomassBurningEmissions_other_alkanals_decadalmonthlymean1960_v1.nc, \n",
                        "1970\',IPCC_GriddedBiomassBurningEmissions_other_alkanals_decadalmonthlymean1970_v1.nc, \n",
                        "1980\',IPCC_GriddedBiomassBurningEmissions_other_alkanals_decadalmonthlymean1980_v1.nc, \n",
                        "1990\',IPCC_GriddedBiomassBurningEmissions_other_alkanals_decadalmonthlymean1990_v1.nc, \n",
                        "2000\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2005_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2005\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2010_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2010\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2020_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2020\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2030_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2030\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2040_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2040\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2050_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2050\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2060_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2060\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2070_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2070\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2080_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2080\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2090_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2090\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2100_0.5x0.5_v1_21_12_2009.nc, \n",
                        "SOURCE(   2) : \', \n",
                        "FRAC(   1)=\' 1.000\', \n",
                        "1940\',IPCC_GriddedBiomassBurningEmissions_other_alkanals_decadalmonthlymean1940_v1.nc, \n",
                        "1950\',IPCC_GriddedBiomassBurningEmissions_other_alkanals_decadalmonthlymean1950_v1.nc, \n",
                        "1960\',IPCC_GriddedBiomassBurningEmissions_other_alkanals_decadalmonthlymean1960_v1.nc, \n",
                        "1970\',IPCC_GriddedBiomassBurningEmissions_other_alkanals_decadalmonthlymean1970_v1.nc, \n",
                        "1980\',IPCC_GriddedBiomassBurningEmissions_other_alkanals_decadalmonthlymean1980_v1.nc, \n",
                        "1990\',IPCC_GriddedBiomassBurningEmissions_other_alkanals_decadalmonthlymean1990_v1.nc, \n",
                        "2000\',IPCC_GriddedBiomassBurningEmissions_other_alkanals_decadalmonthlymean2000_v1.nc, \n",
                        "2005\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2005_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2010\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2010_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2020\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2020_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2030\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2030_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2040\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2040_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2050\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2050_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2060\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2060_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2070\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2070_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2080\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2080_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2090\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2090_0.5x0.5_v1_21_12_2009.nc, \n",
                        "2100\',IPCC_emissions_RCP85_other_alkanals_biomassburning_2100_0.5x0.5_v1_21_12_2009.nc, \n",
                        "" ;
                :history = "Thu Jun 30 09:04:56 2022: cdo -O merge input/RCP85_ALD2_emis.nc input/RCP85_AONE_emis.nc input/RCP85_BC_emis.nc input/RCP85_C2H6_emis.nc input/RCP85_CH3OH_emis.nc input/RCP85_CH4_emis.nc input/RCP85_CO_emis.nc input/RCP85_ETH_emis.nc input/RCP85_HCHO_emis.nc input/RCP85_NH3_emis.nc input/RCP85_NOx_emis.nc input/RCP85_OC_emis.nc input/RCP85_OLEI_emis.nc input/RCP85_OLET_emis.nc input/RCP85_PAR_emis.nc input/RCP85_RCOOH_emis.nc input/RCP85_SO2_emis.nc input/RCP85_TOL_emis.nc input/RCP85_XYL_emis.nc input/RCP85_ISOP_BIO_emis.nc input/SouthAsia_SDDRE_CHEMISS.nc\n",
                        "Thu Jun 30 09:04:44 2022: cdo -O remap,input/SouthAsia_SDDRE_grid.nc,remapweights.nc input/tfile input/RCP85_ALD2_emis.nc\n",
                        "Thu Jun 30 09:04:44 2022: cdo seldate,1990-01-01T00:00:00,1990-02-01T00:00:00 /home/psingh.iitr/RegCM/REGCM_GLOBEDAT/RCP_EMGLOB_PROCESSED/iiasa//RCP85_ALD2_emis.nc input/tfile\n",
                        "Tue Jun 28 03:15:44 2022: ncbo --op_typ=add ./output/RCP85_ALD2_bb.nc ./output/RCP85_ALD2_ant.nc ./output/RCP85_ALD2_emis.nc" ;
                :NCO = "netCDF Operators version 4.9.1 (Homepage = http://nco.sf.net, Code = http://github.com/nco/nco)" ;
                :CDO = "Climate Data Operators version 2.0.3 (https://mpimet.mpg.de/cdo)" ;

**Comment by praveenvatsh** [comment]
@graziano-giuliani Please help me.

**Comment by praveenvatsh** [comment]
@graziano-giuliani Please help me.

**Comment by praveenvatsh** [comment]
@graziano-giuliani 

/RegCM/Main/chemlib)/mod_che_ncio.F90

 if ( chemi_timeunits(1:6) == 'months' ) then
          ifreq = ifrqmon
        else if ( chemi_timeunits(1:4) == 'days' ) then
          ifreq = ifrqday
        else if ( chemi_timeunits(1:5) == 'hours' ) then

Changed the months to month, and "Fatal in file: mod_che_ncio.F90 at line: 516 NO CODED FREQUENCY IN CHEMISS FILE" error is gone.
But now getting new errors...

Unrecognized unit of measure for time string.
 Offending timeunit string :month since 1940-01-15 00:00:00
 chem emission : time record not found emission file
 -------------- FATAL CALLED ---------------
  Fatal in file: mod_che_ncio.F90 at line:      554
 IO ERROR in CHEM EMISSION

Is this because of the type of calendar selection?

**Comment by praveenvatsh** [comment]
@graziano-giuliani 

All the above problems are solved.
Now getting the error "OXBC FILE ERROR."

Please help to solve this.

**Comment by praveenvatsh** [comment]
@graziano-giuliani 

For chemsimtype "AERO"

**Comment by praveenvatsh** [comment]
@graziano-giuliani 

Found the solution.

**Comment by lhba87** [comment]
@singhpraveenk, Good aftrnoon (from Brazil). I'm having the same problems you had. Could you put your solutions for every step? I am currently in the first one, but following this discussion, I believe that solving that would succeed to the next one.
Thank you.
