### ISSUE TITLE
Supported EC-Earth3-Veg model not updated in mod_cmip6_helper.F90

### ISSUE THREAD

**Issue by jingxiangchung** [ICTP/RegCM#25]
"EC-Earth3-Veg" is the current supported CMIP6 GCM in RegCM, however, in the file mod_cimp6_helper.F90, "EC-Earth3" was listed instead. This created conflict when either "EC-Earth3-Veg" or "EC-Earth3" was specified in the namelist file. Hopefully this issue can be rectified by the developers.

**Comment by graziano-giuliani** [comment]
Thanks, this is now fixed in master 1064b20c33bf297907402bade78a7f4d75ba9045 and 53c3fb4b1efce80f63937868f4cab181f3180e74
