### ISSUE TITLE
Is it Possible to Generate ICBC Files from CMIP6 Files Stored Locally?

### ISSUE THREAD

**Issue by jingxiangchung** [ICTP/RegCM#26]
Dear developers,

I am in the process of conducting dynamical downscaling on CMIP6 outputs for Southeast Asia region. I am wondering could RegCM allows the SST and ICBC files to be generated from the CMIP6 GCMs output stored on my local hard disk? The current approach which pulls the GCMs information over the OpenDAP while useful, can be quite unstable and sometimes broken. I imagine the solution would be to replace the OpenDAP link with the path to those CMIP6 GCMs output stored locally, but I am not skillful enough to edit the source code. Hope you or anyone can help on this. 

Thanks!

**Comment by graziano-giuliani** [comment]
It is possible to replace cmip6_inp with a path on disk. BUT the remaining part of the path must be like it is on the ESGF server. You can always anyway edit the mod_cmip6_helper.F90 to change this, though: it should not be overwhelmingly difficult even without programming skills. The relevant part is in the creation of the fpath in the two subroutines cmip6_fxpath and cmip6_path.

**Comment by jingxiangchung** [comment]
Thanks a lot Graziano for the prompt reply, but unfortunately I just managed to find the time to test it out. I opted for the path not editing mod_cmip6_helper.F90 and it works. Perhaps I will share the steps I used here for other users who might be less tech savvy:

1. Edit the "cmip6_inp" in the namelist file pointing to the folder we want.
2. Run the SST program. The goal here is to get the ESGF-server-like path we need to create from the error message. You can check the path needed at the line starting with "mod_cmip6_hadmm.F90 :      429:Error opening file"
3. Create the path required in the our folder.
4. Place/link all the CMIP6 files required by RegCM to that path we created in step 3.
5. Re-run the SST program. Everything should work fine here onwards.
