### ISSUE TITLE
Lambert projection CRS missing semi_minor_axis attribute

### ISSUE THREAD

**Issue by jalder-usgs** [ICTP/RegCM#30]
When using a Lambert projection, the semi_major_axis attribute is written into the CRS variable, but it is missing the corresponding semi_minor_axis. Granted RegCM uses a spheroid where semi_major_axis = semi_minor_axis, but some Java based visualization tools (such as Panoply) fail to map and project the data with only semi_major_axis written into CRS.

**Comment by graziano-giuliani** [comment]
Issue fixed in d0cfb53adfd03f4078dfcf40003c0bc8f966cff4
