### ISSUE TITLE
grid_factor set to 0.0 for Lambert projection

### ISSUE THREAD

**Issue by jalder-usgs** [ICTP/RegCM#33]
In RegCM 5.0.0, the grid_factor in the NetCDF global attributes is being set to 0.0 for a Lambert projection. For standard parallels of 30N and 60N it should be ~0.72.

**Comment by graziano-giuliani** [comment]
Fixed in ictp_devel aa2b75b8c2fbb1ab2b3b89b1b87d38fc90786b29
