### ISSUE TITLE
Fatal Called: While Running regcmMPI on RegCM-5.0.0

### ISSUE THREAD

**Issue by AsyamMD** [ICTP/RegCM#38]
Hi, I've been trying the tutorial but stumble upon this error while running the regcmMPI:

  This is RegCM 5
   GIT Revision: 5.0.0 compiled at: data : Oct 11 2023  time: 21:06:38

 : this run start at  : 2023-10-14 00:34:41+0700
 : it is submitted by : asyam
 : it is running on   : LEGION-JEJE
 : it is using        :            4   processors
 : in directory       : /home/asyam/regcm-run

 CPUS DIM1 =            4
 CPUS DIM2 =            1

 Reading model namelist file
 -------------- FATAL CALLED ---------------
  Fatal in file: mod_params.F90 at line:     2690
 Error reading PHYSICSPARAM
 -------------------------------------------
 mod_params.F90 :     2690:            1
 Abort called by computing node            0 at 2023-10-14 00:34:41.930 +0700
 Execution terminated because of runtime error
Abort(1) on node 0 (rank 0 in comm 496): application called MPI_Abort(comm=0x84000003, 1) - process 0

These are the library lists that I used:

- HDF 1.14.1-2
- Jasper 1.900.1
- LibPNG 1.6.39
- NCEPlibs 
- netcdf-c 4.9.2
- netcdf-fortran 4.6.0
- pnetcdf 1.12.3
- zlib 1.2.13

**Comment by AsyamMD** [comment]
Just for future reference: anyone that faced this kind of error (*PARAM), most of the times are caused by mismatch on the namelist (depending on which PARAM does not match). Make sure you match your namelist with the one in the Doc directory.

**Comment by lovechang1986** [comment]
Hi,@AsyamDM
I faced the same issue.
There are five items in the physicsparam parameter list in the chem_icbc.F90 file that do not appear in the README.namelist in the Doc folder. They are "ipcpcool", "iwhitecap", "idesseas", "temp_tend_maxval", and "wind_tend_maxval" respectively. All the other parameters are there. In this case, when a similar error still occurs, how should I go about finding the problem?
