### ISSUE TITLE
Conflict about the `mod_oasis` module

### ISSUE THREAD

**Issue by DesmetQuentin** [ICTP/RegCM#53]
Hi Graziano,

I understand the formalism that made you add the "empty" `mod_oasis` module in `mod_oasis.F90`, but it's a problem when compiling with `--enable-oasis` because the OASIS library itself is called `mod_oasis` (see import in, e.g., `oasislib/mod_oasis_generic.F90` or `mod_oasis_interface.F90`). I don't know how do you plan to maintain your `mod_oasis.F90` on the long term, but I think the name should be changed. In the current set up, the compilation with `--enable-oasis` fails when dealing with `mod_oasis_interface.F90` because the import I made in it (`use mod_oasis`) leads to use the `mod_oasis.o` and `mod_oasis.mod` of RegCM's `Main`, instead of the actual OASIS library.

Hope you understand the conflict,
Cheers,
Quentin

**Comment by graziano-giuliani** [comment]
Definitely we have to rename it something else. It was supposed to be a placeholder for anyone wanting to have an entry point at OASIS coupling, and there is actually non need for it in the code (as for BMI, also).  40d51763b

**Comment by graziano-giuliani** [comment]
Sorry, some more went into the commit... This is the correct: 9981aee6f9acff687ffdc8e4d9b29b1481648597

**Comment by DesmetQuentin** [comment]
Well, off course it also works by deleting it :+1: (I checked compilation, it's alright now)
See you later!
Quentin
